### ISSUE TITLE
[ProjectTracking]: congestion control milestone 2

### ISSUE THREAD

**Issue by akhi3030** [near/near-one-project-tracking#11]
All information below was gathered by @akashin.  I am filling it out on his behalf.

# Goals

## Current status

Right now we have fully implemented [Local Congestion Control](https://docs.google.com/document/d/1X-GRMJgmwYuZwfocMxmXhxYYBze_t52GdgebtXLhlkk/edit#bookmark=id.ghujalgjx6r), meaning that shard validators and RPC nodes will not be overloaded by transactions coming into their local transaction pools and receipts generated from local transactions.

Technically, this is achieved by introducing two limits:
- The size of the local transaction pool for each shard is limited to 100MB, after the limit is reached, the node stops accepting new transactions. This limit is [configurable](https://github.com/near/nearcore/pull/9172/files)
- The size of the delayed receipts queue is [limited to 20,000 receipts](https://github.com/near/nearcore/pull/9222/files), after the limit is reached, the chunk producer will stop including new receipts in the chunk. This limit is not configurable but is not yet enforced by consensus

For the exact implemented features see https://github.com/near/nearcore/milestone/26?closed=1

## Next steps

Local Congestion Control only limits local congestion sources but ignores global sources of congestion such as receipts incoming from the other shards. The [Global Congestion Control](https://docs.google.com/document/d/1X-GRMJgmwYuZwfocMxmXhxYYBze_t52GdgebtXLhlkk/edit#bookmark=id.sjw2d720i0v7) milestone aims to address this by introducing a global limit on the number/size of delayed receipts that are present in the queues across all shards.

Technically, this can be achieved through:
- Communicating information about the per-shard size of delayed receipts by including it in the chunk header
- Chunk producers should stop including new receipts in the chunk when the *aggregate* size of delayed receipts across all shards is more than some threshold (e.g. 100MB)

The high-level outline of technical work can be found at https://github.com/near/nearcore/milestone/27

See the meeting notes for the [relevant discussion](https://docs.google.com/document/d/1KcR9WOLI6uFtbVsXuG3K_3WisndFi6X-WUEGCfxtuEg/edit#bookmark=id.5d1tcifjrx7b).

As a nice to have, we can enforce this constraint at a protocol level, though this is arguably a low-priority attack vector.

# Links to external documentations and discussions

- [State of congestion control in September 2023](https://docs.google.com/document/d/1rEY0-4b9NkEu3WUwOQ-fkmc0wGwRszgH0EJNBU2aitM/edit).  This document also provides links to additional docs.
- [Zulip thread](https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/State.20of.20Congestion.20Control.2C.20Sep.202023)

# Estimated effort

TODO.  Nominally all the engineering effort should be in code owned by the core team.  In the past engineers from the runtime team have also contributed and may contribute in future as well.

# Assumptions

TODO

# Pre-requisites

TODO

# Out of scope

TODO.  I believe that this project should just be for implementing global congestion control.  The related project for transaction priority should be tracked in a different project.

**Comment by jakmeier** [comment]
I suggest we close this issue in favour of its successor https://github.com/near/near-one-project-tracking/issues/48#Out-of-scope
