### ISSUE TITLE
Explorer frontend (Bohdan + Andrei)

### ISSUE THREAD

**Issue by gmilescu** [near/near-one-project-tracking#37]

**Comment by khorolets** [comment]
2024-01-20 - Figure out how the existing legacy Explorer is set up and what must be done to add more statelessness. I synced about it with @ecp88 to confirm a couple of things. We will need:
- spin up an instance of `explorer-backend` (nodejs) similar to existing mainnet and testnet
- adjust a config on the `explorer-frontend-prod` instance side to add additional network
- We will require a dedicated domain (I'd prefer statelessnet.explorer.near.org @ecp88 to have access and be ready to assist us with that). Domain is a way the legacy Explorer differentiates networks, so I'd follow it to avoid inventing a wheel

**Comment by khorolets** [comment]
2024-01-31: 
I was making the last preparations of the configs to set up the things mentioned in the previous comment. Then I realized I did it in the wrong terraform files. Fortunately, I did no harm 😬. I hope to be able to finish it tomorrow.

**Comment by khorolets** [comment]
2024-02-19:
And it's alive https://legacy.explorer.statelessnet.near.org/blocks

It could have been done since Feb 16, but I messed up with the network config and figured it only today 🤦‍♂️

Notes:
- Node telemetry is unavailable (I guess I can configure it if necessary)
- Analytics is not support (we don't want to run an additional service to collect it for Stake Wars, so no fancy charts, sorry)

**Comment by khorolets** [comment]
@andrei-near Sorry for the delay in getting back to you with the response.

This is a list of parameters that telemetry captures.

https://github.com/near/near-explorer/blob/master/backend/src/router/telemetry.ts#L24-L59

And I've found this https://github.com/near/near-explorer/blob/master/backend/src/utils/telemetry.ts 🤔 which if I read it correctly means, that potentially NEAR Explorer can initiate a telemetry schema in a given database by itself. I can give it a try if it is still needed.
