### ISSUE TITLE
[ProjectTracking]: Add support for the Dencun Ethereum upgrade to rainbow bridge

### ISSUE THREAD

**Issue by akhi3030** [near/near-one-project-tracking#51]
# Goals
The Ethereum Dencun Upgrade, blending “Deneb” and “Cancun” into its name, represents a significant milestone in Ethereum’s ongoing evolution. Targeting both the Consensus Layer (CL) and Execution Layer (EL), Dencun is poised to introduce a series of improvements aimed at enhancing Ethereum’s scalability, security, and overall network efficiency. 

The Dencun upgrade will require making various changes to the rainbow bridge.

Changes included in the Network Upgrade that affect the bridge.

* [EIP-4788: Beacon block root in the EVM ](https://eips.ethereum.org/EIPS/eip-4788) - affect the execution layer
Commit to the hash tree root of each beacon chain block in the corresponding execution payload header.
Store each of these roots in a stateful precompile.

* [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844) - affect the both execution and consensus layer
Introduce a new transaction format for “blob-carrying transactions” which contain a large amount of data that cannot be accessed by EVM execution, but whose commitment can be accessed. The format is intended to be fully compatible with the format that will be used in full sharding.

The list of components that require changes and updates:
[Validators](https://github.com/aurora-is-near/eth2-on-near-client-validator)
[Prover contract](https://nearblocks.io/address/prover.bridge.near)
[Light client contract](https://nearblocks.io/address/client-eth2.bridge.near)
[ETH-to-NEAR event relayer](https://github.com/aurora-is-near/eth-to-near-event-relayer)
[ETH-to-NEAR blocks relayer](https://github.com/aurora-is-near/rainbow-bridge/tree/master/eth2near/eth2near-block-relay-rs)

The upgrade schedule for networks is as follows:
Goerli Testnet - 17 Jan 2024 @ 06:32 UTC (epoch 231680)
Sepolia Testnet - 30 Jan 2024 @ 22:51 UTC (epoch 132608)
Holesky Testnet - 07 Feb 2024 @ 11:34 UTC (epoch 29696)
Mainnet - (March 13, 2024, 01:55:35pm UTC)

# Links to external documentations and discussions
https://hackmd.io/5qs4ATeqSQmloRbIEy8ycw

# Estimated effort
6 weeks

# Assumptions

N/A

# Pre-requisites

N/A

# Out of scope

N/A

**Comment by karim-en** [comment]
March 8th update:

- The bridge on Goerli has been updated
- The validators on Mainnet has been.
- The Prover contract will be updated by the end of the day.

**Comment by karim-en** [comment]
March 13th update:
What left to do before the upgrade on March 13, 2024, 01:55:35pm UTC:
* Upgrade client contract 
* Update the Ethereum nodes (lodestar and geth)
* Update the blocks and events relayers services

**Comment by akhi3030** [comment]
Now done.
